from enum import Enum


class Category(str, Enum):
    BEBIDAS = "BEBIDAS"
    ABARROTES_SECOS = "ABARROTES_SECOS"
    CAFE_INFUSIONES = "CAFE_INFUSIONES"
    LACTEOS = "LACTEOS"
    CARNES = "CARNES"
    SNACKS_GOLOSINAS = "SNACKS_GOLOSINAS"
    CUIDADO_PERSONAL = "CUIDADO_PERSONAL"
    LIMPIEZA_HOGAR = "LIMPIEZA_HOGAR"
    BEBES = "BEBES"
    MASCOTAS = "MASCOTAS"
    OTROS = "OTROS"