@host = http://localhost:8000
@baseUrl = {{host}}

### ===========================================
### Registrar usuario
### ===========================================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "dni": "12345678",
  "names": "Juan",
  "last_names": "Pérez Gómez",
  "username": "juan",
  "password": "12345678",
  "role": "ADMIN"
}

### Iniciar sesión (ADMIN)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "juan",
  "password": "12345678"
}

